# Site settings
title: cool father | 程序员爸爸
email: taoliapp@163.com
description: > # this means to ignore newlines until "baseurl:"
  Be a good man, be a good father, be a good programmer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.taoliapp.com" # the base hostname & protocol for your site
twitter_username:
github_username:  vulcan

# Build settings
markdown: kramdown
